@echo off
REM codex stub binary for CI end-to-end host driver tests (direction C, ADR-0018).
REM Mimics codex exec --skip-git-repo-check: print artifact-bearing output, exit 0.
echo [codex-stub] task received
echo Generated artifact: src/generated/stub_output.go
echo package main
echo // stub-generated by codex stub binary (CI e2e)
echo func main() {}
exit /b 0
